### ISSUE TITLE
Bug: filter radio buttons on iOS show a visual bug

### ISSUE THREAD

**Issue by ivanseed** [ivanseed/gitstats#2]
On iOS Safari the filter buttons display along with a radio checkbox.

Example:
![image](https://user-images.githubusercontent.com/8760543/31079695-6328e1a6-a77e-11e7-9efe-9878e1b7bf85.png)

**Comment by Athyk** [comment]
Working on it

**Comment by Athyk** [comment]
I Changes the issue in my latest commit. however I can't send a new pull request just yet as the other hasn't been accepted. But you will find the fix here: https://github.com/Athyk/gitstats/commit/9233fe2540cb2dd3757b0ea9c4588f131ea7a0a2

**Comment by ivanseed** [comment]
Done as part of PR #12
