### ISSUE TITLE
Feature: add drop down to additionally filter by language

### ISSUE THREAD

**Issue by ivanseed** [ivanseed/gitstats#3]
There should be a drop-down menu that allows a user to select one of the popular languages on GitHub. This filter should additionally work with the 3 buttons so we should be able to filter by stars + language for example.

**Comment by SioJL13** [comment]
Hey @ivanseed do I only need to clone and run npm install in order to make the project work? I ran into some errors when I tried that. Thanks!

**Comment by bhagatparwinder** [comment]
I'll add it.

**Comment by ivanseed** [comment]
Hey @SioJL13 , that should be it! What error are you running into? It could be to do with npm versioning.

**Comment by ivanseed** [comment]
Done as part of #38
