### ISSUE TITLE
Feature: Replace Nprogress with a React loader component

### ISSUE THREAD

**Issue by ivanseed** [ivanseed/gitstats#31]
At the moment I am using [nprogress](http://ricostacruz.com/nprogress/) for the top loading bar, however, this is not ideal as it directly accesses `document` and really everything should be going through the VDOM. 

Write your own component, or find a 3rd party React component that achieves the same results as the current implementation of the loading bar. It should keep/be as close as possible to the same visual effect.

**Comment by uppe-r** [comment]
Looks to be pretty simple, I gotcha 😉
