### ISSUE TITLE
Feature: Replaces icons with Octicons

### ISSUE THREAD

**Issue by ivanseed** [ivanseed/gitstats#39]
Replace/refactor code to allow for the use of Octicons.

https://octicons.github.com/

**Comment by bomholtm** [comment]
You want to replace all the svg with in `<div class="search-container">` and `<div class="repositories">`  with octicons?
Would love to help!

**Comment by ivanseed** [comment]
@bomholtm Yes, please! So we can get rid of the SVG files and also the files that contain the inline SVG code.

**Comment by bomholtm** [comment]
@ivanseed It will be my first real PR and I am not that familiar with the technologies you used, but I will start working on it as soon as I get home (I think I figured out most of it already).
Is there an easy way of contacting you if I have any questions (for example gitter)?

**Comment by ivanseed** [comment]
@bomholtm That is no problem, probably the best way would be through discord if you have that? Or you can open up a PR and post any comments on that.

**Comment by bomholtm** [comment]
@ivanseed It seems like I can't figure out how to import a css file from node_modules. When using a cdn link for octicons.css everything seems to work.
Also installed discord but don't know how to add you.

**Comment by ivanseed** [comment]
@bomholtm My discord user name is Zeb#9743 if you send me a request I will add you.
