### ISSUE TITLE
Bug: Fix npm test command

### ISSUE THREAD

**Issue by rafaelklaessen** [ivanseed/gitstats#43]
When I ran `npm test` I got the following error: `Cannot find module 'babel-eslint'`
I proceeded to install eslint and babel-eslint, but npm install failed with:
`Cannot read property '0' of undefined`
Then, after trying 3 times, somehow eslint was installed and I could run the tests.

However, this does cause the travis build to fail and it's pretty inconvenient.
I think it's some weird thing with de deps

**Comment by ivanseed** [comment]
Yes, definitely needs looking into, I am not sure why this is happening.

**Comment by J-Wicks** [comment]
I think I've managed to fix this by clearing the npm cache and reinstalling everything. I no longer get an error when running the test script. I'll submit a PR for you to take a look.
