### ISSUE TITLE
Question regarding sorting based on Last Modified Date/Time

### ISSUE THREAD

**Issue by PriyankaGitHub7** [ivanseed/gitstats#48]
I have observed that the repositories are not sorted in the descending order of last modified date/time. The repo updated on 4th October is displayed between two repositories on October 8th as shown in the screenshot below. Many such instances can be seen. 

![image](https://user-images.githubusercontent.com/10359471/31315012-1ee12118-ac2c-11e7-9e1a-769a47fb7569.png)

@ivanseed Could you please check this and confirm if this is an issue or if I am missing something. Thank you.

**Comment by ivanseed** [comment]
Hey, this was actually resolved by #33 but just hasn't been built and not live yet! Will fix that now. If you were to checkout master it would work correctly locally.
