### ISSUE TITLE
QoL: Improve the readme

### ISSUE THREAD

**Issue by ivanseed** [ivanseed/gitstats#5]
The readme is very bare. Please add information on what this app does, and how to get the development environment up and running.

**Comment by PriyankaGitHub7** [comment]
@ivanseed Will take this up.

**Comment by ivanseed** [comment]
Thanks @PriyankaGitHub7

**Comment by haroon-sheikh** [comment]
@PriyankaGitHub7 @ivanseed should we also add a screenshot of the app? E.g. https://github.com/equinusocio/material-theme

**Comment by PriyankaGitHub7** [comment]
@ivanseed Raised the pull request https://github.com/ivanseed/gitstats/pull/20. Please check and let me know your comments.
