### ISSUE TITLE
Add more useful stats to the tiles

### ISSUE THREAD

**Issue by ivanseed** [ivanseed/gitstats#54]
Is there anything else that could be added onto the tiles that is interesting? At the moment we only show the name of the repo, description, basic stats and last updated. Is there anything else we can show?

Bonus points if you somehow get some cool graphs in.

**Comment by titeller** [comment]
I add owner avatar on titles
Please review my pr #62

**Comment by ivanseed** [comment]
@titeller Thats for the PR, I made a tiny adjustment but its now in master! Thanks for contributing.
