### ISSUE TITLE
Update footer with link to Github and License 

### ISSUE THREAD

**Issue by ivanseed** [ivanseed/gitstats#55]
So the footer already links to GitHub with the text 'GitStats' however I want a small a small bit of text under that, before the contributor list that says something along the lines of 'Fork me on GitHub' which will be the hyperlink to this repo instead of the current implementation. 

Also on the same line or a new line, which ever you think looks better; add link to the MIT licence. Text would look something like "MIT License Copyright (c)" or something along those lines. Whatever you think looks best.

**Comment by thepriefy** [comment]
Can the hyperlink to this repo (before the contributor list) be a github button? Something like this.
![fireshot capture 72 - github_buttons - https___buttons github io_](https://user-images.githubusercontent.com/10849586/31473899-8439754a-af21-11e7-86bf-b776c50a2219.png)

**Comment by ew4321** [comment]
I'll try to work on this.

**Comment by Rud156** [comment]
Just created a PR for this issue!

**Comment by KatSaldivar** [comment]
I also made a PR that has both the license link as well as the repo link.

**Comment by ivanseed** [comment]
Thanks @thepriefy @Rud156 @KatSaldivar , I have combined all PRs into one. Thank you for contributing!
