### ISSUE TITLE
Add support for GitHub emojis

### ISSUE THREAD

**Issue by ivanseed** [ivanseed/gitstats#63]
The description of some of the projects coming from the API include github emojis. However they are currently not being rendered, find a way to render them!

**Comment by ncaron** [comment]
#68 works and is a good solution but it does not handle unsupported emojis, like :atom: and will only render `:atom:`. Which, in my opinion, is ugly. #67 handles this with an inline function to replace unsupported emojis with an empty string.

Both Pull Requests - Supported emojis display correctly
![both](https://user-images.githubusercontent.com/13804601/31524019-5a4ca3e4-af8d-11e7-9e3c-3f87cc3c7fae.png)

#68 - Doesn't handle unsupported emojis
![68](https://user-images.githubusercontent.com/13804601/31524033-67fd2d7e-af8d-11e7-8484-a45734b3af0e.png)

#67 - Handles unsupported emojis
![67](https://user-images.githubusercontent.com/13804601/31524037-6ceecf90-af8d-11e7-8791-5635c8d3445e.png)

**Comment by ivanseed** [comment]
@ncaron You are correct I have merged both PRs in but currently #68 has overwritten your changes. I will revert this for the use case when Emojis cannot be rendered. Both implementations are sound - at the end of the day hope you both understand that I could have only one in the repo 😅 . Both still count towards Hacktoberfest though!

**Comment by ncaron** [comment]
It's all good! #68 does look cleaner, maybe there's a way to handle unsupported emojis with react-emoji-render but I couldn't really find anything. I'm still new to all of this :grinning:
