### ISSUE TITLE
Feature: add a site footer

### ISSUE THREAD

**Issue by ivanseed** [ivanseed/gitstats#7]
Add a footer that fits in with the style of the site. It must contain a link to this repository, you have full creative control.

Bonus:
Add the list of contributors to this project in the footer.

**Comment by Athyk** [comment]
Working on it

**Comment by Athyk** [comment]
Done, hope this is what you had in mind. For any other changes feel free to tag me in other issues relating, design/css or html. https://github.com/ivanseed/gitstats/pull/12

**Comment by Athyk** [comment]
#12
